// This file is auto-generated by `pnpm db:gen-types`.
// Do not edit manually.
//
// To regenerate, run: pnpm db:gen-types
// Requires local Supabase to be running: pnpm db:start

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

import type { SupabaseClient } from "@supabase/supabase-js";

export type TypedSupabaseClient = SupabaseClient<Database, "public", "public">;

export type Database = {
  public: {
    Tables: {
      rooms: {
        Row: {
          id: string;
          code: string;
          game_type: string;
          status: string;
          host_player_id: string | null;
          max_players: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          game_type: string;
          status?: string;
          host_player_id?: string | null;
          max_players?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          game_type?: string;
          status?: string;
          host_player_id?: string | null;
          max_players?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      players: {
        Row: {
          id: string;
          room_id: string;
          nickname: string;
          is_host: boolean;
          is_connected: boolean;
          user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          nickname: string;
          is_host?: boolean;
          is_connected?: boolean;
          user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          nickname?: string;
          is_host?: boolean;
          is_connected?: boolean;
          user_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      game_sessions: {
        Row: {
          id: string;
          room_id: string;
          game_type: string;
          round_number: number;
          started_at: string;
          ended_at: string | null;
          result: Json | null;
        };
        Insert: {
          id?: string;
          room_id: string;
          game_type: string;
          round_number?: number;
          started_at?: string;
          ended_at?: string | null;
          result?: Json | null;
        };
        Update: {
          id?: string;
          room_id?: string;
          game_type?: string;
          round_number?: number;
          started_at?: string;
          ended_at?: string | null;
          result?: Json | null;
        };
        Relationships: [];
      };
      spyfall_locations: {
        Row: {
          id: string;
          name: string;
          image_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          image_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          image_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      spyfall_roles: {
        Row: {
          id: string;
          location_id: string;
          name: string;
          image_url: string | null;
          max_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          name: string;
          image_url?: string | null;
          max_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          location_id?: string;
          name?: string;
          image_url?: string | null;
          max_count?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      spyfall_games: {
        Row: {
          id: string;
          session_id: string;
          location_id: string;
          spy_count: number;
          timer_duration: number;
          has_moderator: boolean;
          moderator_player_id: string | null;
          tie_break_rule: string;
          phase: string;
          phase_started_at: string | null;
          spy_guess_location_id: string | null;
          winner: string | null;
        };
        Insert: {
          id?: string;
          session_id: string;
          location_id: string;
          spy_count?: number;
          timer_duration?: number;
          has_moderator?: boolean;
          moderator_player_id?: string | null;
          tie_break_rule?: string;
          phase?: string;
          phase_started_at?: string | null;
          spy_guess_location_id?: string | null;
          winner?: string | null;
        };
        Update: {
          id?: string;
          session_id?: string;
          location_id?: string;
          spy_count?: number;
          timer_duration?: number;
          has_moderator?: boolean;
          moderator_player_id?: string | null;
          tie_break_rule?: string;
          phase?: string;
          phase_started_at?: string | null;
          spy_guess_location_id?: string | null;
          winner?: string | null;
        };
        Relationships: [];
      };
      spyfall_player_roles: {
        Row: {
          id: string;
          game_id: string;
          player_id: string;
          role_id: string | null;
          is_spy: boolean;
        };
        Insert: {
          id?: string;
          game_id: string;
          player_id: string;
          role_id?: string | null;
          is_spy?: boolean;
        };
        Update: {
          id?: string;
          game_id?: string;
          player_id?: string;
          role_id?: string | null;
          is_spy?: boolean;
        };
        Relationships: [];
      };
      spyfall_votes: {
        Row: {
          id: string;
          game_id: string;
          voter_player_id: string;
          target_player_id: string;
          vote_round: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          voter_player_id: string;
          target_player_id: string;
          vote_round?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          voter_player_id?: string;
          target_player_id?: string;
          vote_round?: number;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
